### ISSUE TITLE
Playlist downloading is failed time to time

### ISSUE THREAD

**Issue by str1k3r** [svbnet/RedSea#3]
It might fail on the random playlist, but usually it fails on the same place when I'm trying to download the same playlist again. Error all time is the same HTTP404:

```
Traceback (most recent call last):
  File "./redsea.py", line 116, in <module>
    main()
  File "./redsea.py", line 102, in main
    md.download_media(track, config['tidal']['quality'], media_info)
  File "/home/sergey/RedSea/mediadownloader.py", line 107, in download_media
    album_info = self.api.get_album(track_info['album']['id'])
  File "/home/sergey/RedSea/tidal_api.py", line 56, in get_album
    return self._get('albums/' + str(album_id))
  File "/home/sergey/RedSea/tidal_api.py", line 24, in _get
    raise TidalError(resp)
tidal_api.TidalError: 2001: Album [45150999] not found (HTTP 404)

```
Affected playlists (few examples):
8fba833d-e395-4f06-a3eb-4a60959ef5c7
46e8e130-68d2-47bb-9e47-ff2f42d3093b

**Comment by svbnet** [comment]
It seems like in Tidal-curated playlists, whatever generates them adds "unstreamable" tracks to the playlist. However, the problem is that the unstreamable tracks it adds exist within Tidal, but for some reason attempting to get the album or track metadata through the client API will return a 404, even though they definitely exist: if you click the "play in tidal" button on [this](http://tidal.com/track/61673931), it will say it's no longer available. Therefore the reason it errors out is because I didn't check for the `allowStreaming` property on responses, as I had literally never encountered a media object which had this set to false, so thanks for the detailed report.

**Comment by str1k3r** [comment]
Yes, playlists are Tidal-curated. 

Could you add option which can allow to skip such tracks and continue script execution. It will be very useful on huge batches :) 

Thanks.
